### ISSUE TITLE
where can i run this?

### ISSUE THREAD

**Issue by KendallDoesCoding** [aliraza944/GameController#1]
android studio?

**Comment by aliraza944** [comment]
This is a react native boilerplate code I have created for myself to be used in future projects.  Its just boilerplate.

**Comment by KendallDoesCoding** [comment]
> This is a react native boilerplate code I have created for myself to be used in future projects. Its just boilerplate.

Ok cool.

**Comment by KendallDoesCoding** [comment]
@aliraza944 Have you used this in any of your projects, can I have a look
