### ISSUE TITLE
Please have a look

### ISSUE THREAD

**Issue by KendallDoesCoding** [aliraza944/GameController#2]
You don't have a discussions page on your GitHub so posting it here: https://github.com/KendallDoesCoding/mogul-christmas/issues/262

**Comment by aliraza944** [comment]
Oh yeah sure. I will have look at it. I am quite busy right now with my work, So I will definitely have look at it on weekends.

**Comment by KendallDoesCoding** [comment]
> Oh yeah sure. I will have look at it. I am quite busy right now with my work, So I will definitely have look at it on weekends.

Thanks a lot!

**Comment by KendallDoesCoding** [comment]
@aliraza944 Did you get a chance to check it out?

**Comment by KendallDoesCoding** [comment]
How are you doing @aliraza944?

**Comment by aliraza944** [comment]
I am great. Thanks. I am looking at the code and you guys have done a great job building the site. @KendallDoesCoding you should shift your site to NEXT js if you want better state management.

**Comment by KendallDoesCoding** [comment]
> I am great. Thanks. I am looking at the code and you guys have done a great job building the site. @KendallDoesCoding you should shift your site to NEXT js if you want better state management.

Good to know! It's been a long time... Thanks a lot.

Yeah, 3 people (inculding you) had told me to this this in the past, and I had created the issue: https://github.com/KendallDoesCoding/mogul-christmas/issues/189 and repo, although all of you who were supposed to help me, have gotten busy with your own work which is really understandable, so I closed the issue a few days back as I do not want to inconvenience yall, but we will surely do that in the future once yall or other people are down to help me :)

**Comment by aliraza944** [comment]
You are right I got really busy with my own projects, and I still am. But I will help you out with any kind of guidance or the code reviewing process . if I got enought time I will definately sove some issues as well.

**Comment by KendallDoesCoding** [comment]
Hi. The thing is node doesn't work on my laptop and PC. So I haven't really
gotten into node, react and next.js, so I will need someone who knows to do
atleast 80% of the work and I will do 20% (obviously they can add it in
their resume, portfolio and consider it their own project as well) so if I
find soneone who can help do that. Will definitely do the Next.js thing, as
it seems to be a great idea!
